### ISSUE TITLE
Subcraft rotation fail

### ISSUE THREAD

**Issue by mwkaicz** [msummers123/Movecraft-3#102]
```[00:59:53 WARN]: [Movecraft] Task #52 for Movecraft v3.1.X75 generated an exception
java.lang.NullPointerException
        at net.countercraft.movecraft.async.rotation.RotationTask.getMinX(RotationTask.java:525) ~[?:?]
        at net.countercraft.movecraft.async.AsyncManager.processAlgorithmQueue(AsyncManager.java:328) ~[?:?]
        at net.countercraft.movecraft.async.AsyncManager.run(AsyncManager.java:856) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-c46583f-e6f9fd4]
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-c46583f-e6f9fd4]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:694) [spigot.jar:git-Spigot-c46583f-e6f9fd4]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot.jar:git-Spigot-c46583f-e6f9fd4]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot.jar:git-Spigot-c46583f-e6f9fd4]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot.jar:git-Spigot-c46583f-e6f9fd4]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]```

subcraft tower was connected to the RS wire which goes through whole ship

**Comment by eirikh1996** [comment]
I experience the same thing, however, this error does not appear in my server console

**Comment by mwkaicz** [comment]
Exactly this occurs also when craft is connected to whole World. Just can't detect end of the craft.

**Comment by msummers123** [comment]
Fixed
