### ISSUE TITLE
Issue with Movecraft v3.1 X78

### ISSUE THREAD

**Issue by ThatPolishKid99** [msummers123/Movecraft-3#108]
Plugin essentially not responding in any way besides commands,which also don't really work...
1.7.10 Cauldron Server
Here is the section of my startup log with Movecraft and the error
[22:55:37] [Server thread/INFO]: [Movecraft] Enabling Movecraft v3.1.X78
[22:55:37] [Server thread/INFO]: [Movecraft] Recognized PilotTool setting of: 280
[22:55:37] [Server thread/INFO]: [Movecraft] CompatiblityMode is set to true
[22:55:37] [Server thread/INFO]: [Movecraft] Movecraft did not find a compatible version of WorldGuard. Disabling WorldGuard integration
[22:55:37] [Server thread/INFO]: [Movecraft] Found a compatible version of WorldEdit. Enabling WorldEdit integration
[22:55:37] [Server thread/INFO]: [Movecraft] Found a compatible version of Cannons. Enabling Cannons integration
[22:55:37] [Server thread/INFO]: [Movecraft] Found a compatible Vault plugin.
[22:55:37] [Server thread/INFO]: [Movecraft] Loaded 10 Craft files
[22:55:37] [Server thread/ERROR]: Error occurred while enabling Movecraft v3.1.X78 (Is it up to date?)
java.lang.NoClassDefFoundError: com/sk89q/worldedit/world/DataException
	at net.countercraft.movecraft.Movecraft.onEnable(Movecraft.java:176) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415) [CraftServer.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349) [CraftServer.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
	at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:500) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:474) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:434) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:329) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:620) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_25]

**Comment by mwkaicz** [comment]
It Loos like problem with loading WorldEdit try to update it

**Comment by ThatPolishKid99** [comment]
Yes, that worked perfectly thank you!!

**Comment by mwkaicz** [comment]
You're welcome, please close ticket.
