### ISSUE TITLE
Cruise fail

### ISSUE THREAD

**Issue by Uskaanax** [msummers123/Movecraft-3#113]
[21:22:09 INFO]: [Movecraft] Player Uskaanax piloted a craft of type Airship with size 4599 at location: -50 x, 418 z
[21:22:12 INFO]: Uskaanax issued server command: /movecraft:cruise
[21:22:12 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'movecraft:cruise' in plugin Movecraft v3.1.X73
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit-1.8.jar:git-Bukkit-33d5de3]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) ~[craftbukkit-1.8.jar:git-Bukkit-33d5de3]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:625) ~[craftbukkit-1.8.jar:git-Bukkit-33d5de3]
        at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1058) [craftbukkit-1.8.jar:git-Bukkit-33d5de3]
        at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:919) [craftbukkit-1.8.jar:git-Bukkit-33d5de3]
        at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(SourceFile:37) [craftbukkit-1.8.jar:git-Bukkit-33d5de3]
        at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(SourceFile:9) [craftbukkit-1.8.jar:git-Bukkit-33d5de3]
        at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [craftbukkit-1.8.jar:git-Bukkit-33d5de3]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_75]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_75]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:656) [craftbukkit-1.8.jar:git-Bukkit-33d5de3]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:284) [craftbukkit-1.8.jar:git-Bukkit-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:609) [craftbukkit-1.8.jar:git-Bukkit-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:517) [craftbukkit-1.8.jar:git-Bukkit-33d5de3]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
        at net.countercraft.movecraft.listener.CommandListener.onCommand(CommandListener.java:224) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit-1.8.jar:git-Bukkit-33d5de3]
        ... 14 more
[21:22:19 INFO]: Uskaanax issued server command: /release
--------------------------
[21:28:59 INFO]: This server is running CraftBukkit version git-Bukkit-33d5de3 (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)
[21:28:59 INFO]: Checking version, please wait...
[21:29:00 INFO]: You are 37 version(s) behind

**Comment by msummers123** [comment]
You are not using the /cruise command correctly. In the more recent version of the plugin, it checks for this and does not throw an exception. The correct way to use the command would be:
/cruise north
Although using commands like this is not the preferred way of using Movecraft. I would highly recommend signs instead.

**Comment by Uskaanax** [comment]
Thanks. I thought I was on the latest version. I'll re-check again tonight.
