### ISSUE TITLE
Airship wont let me pilot it, error in the log

### ISSUE THREAD

**Issue by mjcrafter100** [msummers123/Movecraft-3#117]
When I try to pilot airship, this is the error I get in the log:
10.04 20:48:31 [Server] WARN at java.lang.Thread.run(Thread.java:745)
10.04 20:48:31 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
10.04 20:48:31 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
10.04 20:48:31 [Server] WARN at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
10.04 20:48:31 [Server] WARN at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:71)
10.04 20:48:31 [Server] WARN at net.countercraft.movecraft.async.AsyncTask.run(AsyncTask.java:36)
10.04 20:48:31 [Server] WARN at net.countercraft.movecraft.async.detection.DetectionTask.excecute(DetectionTask.java:67)
10.04 20:48:31 [Server] WARN at net.countercraft.movecraft.async.detection.DetectionTask.detectSurrounding(DetectionTask.java:242)
10.04 20:48:31 [Server] WARN at net.countercraft.movecraft.async.detection.DetectionTask.detectBlock(DetectionTask.java:95)
10.04 20:48:31 [Server] WARN at org.bukkit.craftbukkit.v1_8_R2.CraftWorld.getBlockAt(CraftWorld.java:88)
10.04 20:48:31 [Server] WARN at org.bukkit.craftbukkit.v1_8_R2.CraftWorld.getChunkAt(CraftWorld.java:124)
10.04 20:48:31 [Server] WARN at net.minecraft.server.v1_8_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:97)
10.04 20:48:31 [Server] WARN at net.minecraft.server.v1_8_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:115)
10.04 20:48:31 [Server] WARN at org.bukkit.craftbukkit.v1_8_R2.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16)
10.04 20:48:31 [Server] WARN at org.bukkit.craftbukkit.v1_8_R2.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295)
10.04 20:48:31 [Server] WARN at org.bukkit.craftbukkit.v1_8_R2.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337)
10.04 20:48:31 [Server] WARN at org.bukkit.craftbukkit.v1_8_R2.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:1)
10.04 20:48:31 [Server] WARN at org.bukkit.craftbukkit.v1_8_R2.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:49)
10.04 20:48:31 [Server] WARN at net.minecraft.server.v1_8_R2.Chunk.addEntities(Chunk.java:820)
10.04 20:48:31 [Server] WARN at net.minecraft.server.v1_8_R2.World.b(World.java:2640)
10.04 20:48:31 [Server] WARN at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14)
10.04 20:48:31 [Server] WARN java.lang.IllegalStateException: Asynchronous entity world add!
10.04 20:48:31 [Server] ERROR Async Task generated an exception.

**Comment by msummers123** [comment]
This sort of error is typically caused by the detection process overflowing the loaded world. IE: you tried to pilot the whole ocean, or an entire continent etc.

To confirm, make sure your craft is surrounded by only air, and try to detect again.

Then check your craft file for what has been added to the allowedblocks that is causing the problem. For example, maybe you accidentally added 8 or 9 to an ocean going ship, or something similar.

**Comment by mjcrafter100** [comment]
But there is nothing in chat like "craft is too large"
Also, I got the airship type file from Bacca's types download on his turret tutorial video, and have done nothing with it.

**Comment by mwkaicz** [comment]
I had same problem few version ago, in some cases this warning doesn't occur and instead of that plugin generates this error.  But I not tested it in latest version.

**Comment by mjcrafter100** [comment]
Yeah, I decided to test that, turned out to be the problem

**Comment by msummers123** [comment]
Sounds like its working then? All right to close the issue?

**Comment by mwkaicz** [comment]
I made few tests and I think that it works correcly now.

**Comment by mwkaicz** [comment]
problem is still there, but only in subcraft rotation (detection says to the player that craft is too big, but then rotation task generates this errror:
```
[22:55:43 WARN]: [Movecraft] Task #92 for Movecraft v3.1.X81 generated an exception
java.lang.NullPointerException
        at net.countercraft.movecraft.async.rotation.RotationTask.getMinX(RotationTask.java:611) ~[?:?]
        at net.countercraft.movecraft.async.AsyncManager.processAlgorithmQueue(AsyncManager.java:332) ~[?:?]
        at net.countercraft.movecraft.async.AsyncManager.run(AsyncManager.java:917) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-1d14d5f-ba32592]
        at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-1d14d5f-ba32592]
        at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:718) [spigot.jar:git-Spigot-1d14d5f-ba32592]
        at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot.jar:git-Spigot-1d14d5f-ba32592]
        at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot.jar:git-Spigot-1d14d5f-ba32592]
        at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot.jar:git-Spigot-1d14d5f-ba32592]
```

im not sure how getting integer can return nullPointerException, maybe task is null?
