### ISSUE TITLE
ERROR PARSING CRAFT FILE FROM DIRECTORY

### ISSUE THREAD

**Issue by atomiccharges** [msummers123/Movecraft-3#178]
I am running a new bukkit 1.8 server and I get an error that says [Server thread/ERROR]: [Movecraft] ***ERROR PARSING CRAFT FILE FROM DIRECTORY : C:\Users\maciek\Desktop\1.8 server run directory\plugins\Movecraft\types\fighter.craft*** I am using the cannon plugin, movecraft and worldedit have made a custom .craft file 
[fighter.zip](https://github.com/msummers123/Movecraft-3/files/112340/fighter.zip)
the complete log is here
[14:26:02] [Server thread/INFO]: Starting minecraft server version 1.8.8
[14:26:02] [Server thread/INFO]: Loading properties
[14:26:02] [Server thread/INFO]: Default game type: SURVIVAL
[14:26:02] [Server thread/INFO]: Generating keypair
[14:26:02] [Server thread/INFO]: Starting Minecraft server on *:25565
[14:26:02] [Server thread/INFO]: Using default channel type
[14:26:02] [Server thread/INFO]: This server is running CraftBukkit version git-Bukkit-07c3001 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
[14:26:02] [Server thread/INFO]: [WorldEdit] Loading WorldEdit v6.1;no_git_id
[14:26:02] [Server thread/INFO]: [Cannons] Loading Cannons v2.3.8
[14:26:02] [Server thread/INFO]: [Movecraft] Loading Movecraft v4.0.1
[14:26:03] [Server thread/INFO]: Preparing level "world"
[14:26:03] [Server thread/INFO]: Preparing start region for level 0 (Seed: -1933276856700590246)
[14:26:03] [Server thread/INFO]: Preparing start region for level 1 (Seed: 4466572232165559396)
[14:26:04] [Server thread/INFO]: Preparing spawn area: 97%
[14:26:04] [Server thread/INFO]: Preparing start region for level 2 (Seed: 4466572232165559396)
[14:26:04] [Server thread/INFO]: [WorldEdit] Enabling WorldEdit v6.1;no_git_id
[14:26:04] [Server thread/INFO]: WEPIF: Using the Bukkit Permissions API.
[14:26:04] [Server thread/INFO]: [WorldEdit] Using com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_8_R3 as the Bukkit adapter
[14:26:04] [Server thread/INFO]: [Cannons] Enabling Cannons v2.3.8
[14:26:05] [Server thread/INFO]: [Cannons] Loading projectile configs
[14:26:05] [Server thread/INFO]: [Cannons] Loading cannon designs
[14:26:05] [Server thread/INFO]: [Cannons] Cannons plugin v2.3.8 has been enabled
[14:26:05] [Server thread/INFO]: [Movecraft] Enabling Movecraft v4.0.1
[14:26:05] [Server thread/INFO]: [Movecraft] Recognized PilotTool setting of: 347
[14:26:05] [Server thread/INFO]: [Movecraft] CompatiblityMode is set to true
[14:26:05] [Server thread/INFO]: [Movecraft] Movecraft did not find a compatible version of WorldGuard. Disabling WorldGuard integration
[14:26:05] [Server thread/INFO]: [Movecraft] Found a compatible version of WorldEdit. Enabling WorldEdit integration
[14:26:05] [Server thread/INFO]: [Movecraft] Found a compatible version of Cannons. Enabling Cannons integration
[14:26:05] [Server thread/INFO]: [Movecraft] Movecraft did not find a compatible version of Towny. Disabling Towny integration.
[14:26:05] [Server thread/INFO]: [Movecraft] Movecraft did not find a compatible version of Essentials. Disabling Essentials integration.
[14:26:05] [Server thread/INFO]: [Movecraft] Could not find compatible Vault plugin. Disabling Vault integration.
[14:26:05] [Server thread/ERROR]: [Movecraft] ***ERROR PARSING CRAFT FILE FROM DIRECTORY : C:\Users\maciek\Desktop\1.8 server run directory\plugins\Movecraft\types\fighter.craft***
[14:26:05] [Server thread/WARN]: java.lang.NullPointerException
[14:26:05] [Server thread/WARN]: 	at net.countercraft.movecraft.craft.CraftType.blockIDMapListFromObject(CraftType.java:118)
[14:26:05] [Server thread/WARN]: 	at net.countercraft.movecraft.craft.CraftType.parseCraftDataFromFile(CraftType.java:219)
[14:26:05] [Server thread/WARN]: 	at net.countercraft.movecraft.craft.CraftType.<init>(CraftType.java:69)
[14:26:05] [Server thread/WARN]: 	at net.countercraft.movecraft.craft.CraftManager.initCraftTypes(CraftManager.java:78)
[14:26:05] [Server thread/WARN]: 	at net.countercraft.movecraft.craft.CraftManager.<init>(CraftManager.java:47)
[14:26:05] [Server thread/WARN]: 	at net.countercraft.movecraft.craft.CraftManager.<clinit>(CraftManager.java:36)
[14:26:05] [Server thread/WARN]: 	at net.countercraft.movecraft.Movecraft.onEnable(Movecraft.java:248)
[14:26:05] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[14:26:05] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[14:26:05] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[14:26:05] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:342)
[14:26:05] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:314)
[14:26:05] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:406)
[14:26:05] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:370)
[14:26:05] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:325)
[14:26:05] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:235)
[14:26:05] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:504)
[14:26:05] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[14:26:05] [Server thread/INFO]: [Movecraft] Loaded 11 Craft files
[14:26:05] [Server thread/INFO]: [Movecraft] Submitted statistics to mcstats.org succesfully. Thank you for your support.
[14:26:05] [Server thread/INFO]: [Movecraft] [V 4.0.1] has been enabled.
[14:26:05] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[14:26:05] [Server thread/INFO]: Done (2,399s)! For help, type "help" or "?"
I dont know what to do

**Comment by Pocketkid2** [comment]
try this, maybe it will help
[fighter.zip](https://github.com/msummers123/Movecraft-3/files/113205/fighter.zip)

**Comment by atomiccharges** [comment]
sorry, same error

2016-02-02 1:21 GMT+01:00 Adam <notifications@github.com>:

**Comment by mwkaicz** [comment]
Your problems are missing spaces, yaml structure can't recognize folders / objects (in this case array lists), each content of each object must have offset two spaces before.


Here is an example where I replaced spacebar with underscore sign:
```
allowedBlocks:
__- 35      #two spaces
flyblocks:  #0 spaces ... it's in root object
__35:      #two spaces
____- 60.0 #four spaces  ( two from root to "35:"  + two from "35:" to "60.0" )
```

Here is correct version of your file, which should works right
```
name: fighter
maxSize: 200
minSize: 20
allowedBlocks:
  - 35
  - 323
  - 324
forbiddenBlocks:
  - 4
blockedByWater: true
speed: 15.0
tryNudge: false
flyblocks:
  35:
    - 60.0
    - 100.0

**Comment by atomiccharges** [comment]
Now it works! Thanks!

2016-02-02 9:42 GMT+01:00 Kai <notifications@github.com>:

**Comment by mwkaicz** [comment]
You're welcome, please close this issue. Thx.
