### ISSUE TITLE
Signs clearing when auto-updating, changes data value of adjacent blocks

### ISSUE THREAD

**Issue by eirikh1996** [msummers123/Movecraft-3#231]
I had placed all the control signs on a craft, and it worked fine. However, once I placed the Status:-sign, all signs was cleared of text, as well as changing data values on adjacent blocks (wool changing colour)

Here is the log output:
[17:28:15] [Server thread/WARN]: [Movecraft] Task #20 for Movecraft v5.5.0 generated an exception
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_9_R1/util/CraftMagicNumbers
	at net.countercraft.movecraft.utils.MapUpdateManager.updateData(MapUpdateManager.java:488) ~[?:?]
	at net.countercraft.movecraft.utils.MapUpdateManager.run(MapUpdateManager.java:932) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.11.jar:git-Spigot-16c940b-0b154b1]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.11.jar:git-Spigot-16c940b-0b154b1]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:730) [spigot-1.11.jar:git-Spigot-16c940b-0b154b1]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.jar:git-Spigot-16c940b-0b154b1]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.jar:git-Spigot-16c940b-0b154b1]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.jar:git-Spigot-16c940b-0b154b1]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
[17:28:20]

**Comment by msummers123** [comment]
Doh! looks like a bug I missed. I'll get on this. Until I get it fixed, better avoid the status sign unless you are in native mode (IE: not compatibilitymode)
