### ISSUE TITLE
Minecraft 1.7.10 Errors

### ISSUE THREAD

**Issue by ThatPolishKid99** [msummers123/Movecraft-3#232]
I'm really sorry, but the Spigot page says its compatiable with 1.7.10. and it does load properly, as seen here, but later I cannot pilot ships. 

> [10:48:58] [Server thread/INFO] [net.countercraft.movecraft.Movecraft/]: [Movecraft] Enabling Movecraft v5.5.0
> [10:48:58] [Server thread/INFO] [net.countercraft.movecraft.Movecraft/]: [Movecraft] Recognized PilotTool setting of: 280
> [10:48:58] [Server thread/INFO] [net.countercraft.movecraft.Movecraft/]: [Movecraft] CompatiblityMode is set to true
> [10:48:58] [Server thread/INFO] [net.countercraft.movecraft.Movecraft/]: [Movecraft] Found a compatible version of WorldGuard. Enabling WorldGuard integration
> [10:48:58] [Server thread/INFO] [net.countercraft.movecraft.Movecraft/]: [Movecraft] Settings: WorldGuardBlockMoveOnBuildPerm - true, WorldGuardBlockSinkOnPVPPerm - true
> [10:48:58] [Server thread/INFO] [net.countercraft.movecraft.Movecraft/]: [Movecraft] Found a compatible version of WorldEdit. Enabling WorldEdit integration
> [10:48:58] [Server thread/INFO] [net.countercraft.movecraft.Movecraft/]: [Movecraft] Found a compatible version of Cannons. Enabling Cannons integration
> [10:48:58] [Server thread/INFO] [net.countercraft.movecraft.Movecraft/]: [Movecraft] Movecraft did not find a compatible version of WGCustomFlags. Disabling WGCustomFlags integration.
> [10:48:58] [Server thread/INFO] [net.countercraft.movecraft.Movecraft/]: [Movecraft] Movecraft did not find a compatible version of Towny. Disabling Towny integration.
> [10:48:58] [Server thread/INFO] [net.countercraft.movecraft.Movecraft/]: [Movecraft] Found a compatible version of Essentials. Enabling Essentials integration.
> [10:48:58] [Server thread/INFO] [net.countercraft.movecraft.Movecraft/]: [Movecraft] Found a compatible Vault plugin.
> [10:48:58] [Server thread/INFO] [net.countercraft.movecraft.Movecraft/]: [Movecraft] Loaded 31 Craft files
> [10:48:58] [Server thread/INFO] [net.countercraft.movecraft.Movecraft/]: [Movecraft] [V 5.5.0] has been enabled.

But, later i get this

> > [10:49:48] [Server thread/WARN] [net.countercraft.movecraft.Movecraft/]: [Movecraft] Task #27 for Movecraft v5.5.0 generated an exception
> java.lang.NullPointerException
> 	at net.countercraft.movecraft.async.rotation.RotationTask.getMinX(RotationTask.java:708) ~[?:?]
> 	at net.countercraft.movecraft.async.AsyncManager.processAlgorithmQueue(AsyncManager.java:404) ~[?:?]
> 	at net.countercraft.movecraft.async.AsyncManager.run(AsyncManager.java:1540) ~[?:?]
> 	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) ~[CraftTask.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
> 	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:346) [CraftScheduler.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:862) [MinecraftServer.class:?]
> 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) [lt.class:?]
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
> 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
> [10:49:50] [Server thread/WARN] [net.countercraft.movecraft.Movecraft/]: [Movecraft] Task #184 for Movecraft v5.5.0 generated an exception
> java.lang.NullPointerException
> 	at net.countercraft.movecraft.craft.CraftManager.removeCraft(CraftManager.java:114) ~[?:?]
> 	at net.countercraft.movecraft.listener.InteractListener$4.run(InteractListener.java:409) ~[?:?]
> 	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) ~[CraftTask.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
> 	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:346) [CraftScheduler.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:862) [MinecraftServer.class:?]
> 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) [lt.class:?]
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
> 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
> [10:49:52] [Server thread/WARN] [net.countercraft.movecraft.Movecraft/]: [Movecraft] Task #188 for Movecraft v5.5.0 generated an exception
> java.lang.NullPointerException
> 	at net.countercraft.movecraft.craft.CraftManager.removeCraft(CraftManager.java:114) ~[?:?]
> 	at net.countercraft.movecraft.listener.InteractListener$4.run(InteractListener.java:409) ~[?:?]
> 	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) ~[CraftTask.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
> 	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:346) [CraftScheduler.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:862) [MinecraftServer.class:?]
> 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) [lt.class:?]
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]

So, i dont know if im just stupid, and did something wrong, but any assistance, even just saying compatibility is not available for 1.7.10, that would be great

side note: this is on Cauldron 1.7.10, cauldron-1.7.10-1.1307.06.218-server

**Comment by msummers123** [comment]
Hello again, this error, the java.lang.NullPointerException
at net.countercraft.movecraft.async.rotation.RotationTask.getMinX(RotationTask.java:708) ~[?:?] is usually caused by a geometry problem. IE: the craft has a weird shape and the engine just can't handle it. I try to fix these when I find them, but there are so many possible shapes some times one gets through that it can't handle. 

The first thing we need to do in troubleshooting is verify that this is the cause. So just make a boring shape like a cube, make sure you can pilot and move that without errors. If that is successful, I would like to know more about the craft shape that is causing the issue. A schematic would be great.

**Comment by ThatPolishKid99** [comment]
Alright, I have made a quick cube, got the engines and furance in, maintaining the shape, and got this
```
[12:40:55] [Server thread/INFO]: ThatPolishKid99 issued server command: /pilot airshipfrigate
[12:40:55] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'pilot' in plugin Movecraft v5.5.0
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PluginCommand.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[SimpleCommandMap.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:717) ~[CraftServer.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1350) [nh.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1132) [nh.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ir.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ir.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.NullPointerException
	at net.countercraft.movecraft.craft.Craft.<init>(Craft.java:66) ~[?:?]
	at net.countercraft.movecraft.listener.CommandListener.onCommand(CommandListener.java:223) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
	... 13 more
```
```
And i also noticed that those previous errors did not occur this time? But I did notice this:
[12:37:49] [Server thread/WARN]: [Movecraft] Task #27 for Movecraft v5.5.0 generated an exception
java.lang.NoSuchFieldError: IRON_TRAPDOOR
	at net.countercraft.movecraft.async.AsyncManager.run(AsyncManager.java:1527) ~[?:?]
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) ~[CraftTask.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:346) [CraftScheduler.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:862) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
```

**Comment by ThatPolishKid99** [comment]
And i also noticed that those previous errors did not occur this time? But I did notice this:
[12:37:49] [Server thread/WARN]: [Movecraft] Task #27 for Movecraft v5.5.0 generated an exception
java.lang.NoSuchFieldError: IRON_TRAPDOOR
	at net.countercraft.movecraft.async.AsyncManager.run(AsyncManager.java:1527) ~[?:?]
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) ~[CraftTask.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:346) [CraftScheduler.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:862) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]

**Comment by ThatPolishKid99** [comment]
whoops, sorry

**Comment by msummers123** [comment]
This error is because it did not find a craft named "airshipfrigate". If you use the /pilot command, and don't specify a correct craft name, that's what causes this.

**Comment by ThatPolishKid99** [comment]
well, then im sorry for completely wasting your time, because it works now.... 
Sorry again
Although, I will ask, do AA and Cannon directors work in 1.7.10?
