### ISSUE TITLE
Movecraft 1.11 Support

### ISSUE THREAD

**Issue by WanderingBread** [msummers123/Movecraft-3#234]
Hello there Mark, 
I have run into an issue while using the plugin in verison 1.11, I attempted to use the version on planet minecraft, however It did not work. I have a small tidbit of the console error:

[09:36:03 WARN]: [Movecraft] Task #22 for Movecraft v5.5.0 generated an exception
java.lang.NoClassDefFoundError: net/minecraft/server/v1_9_R1/World
        at net.countercraft.movecraft.async.AsyncManager.run(AsyncManager.java:1525) ~[?:?]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.11.jar:git-Spigot-31fef09-78c7614]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.11.jar:git-Spigot-31fef09-78c7614]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:730) [spigot-1.11.jar:git-Spigot-31fef09-78c7614]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.jar:git-Spigot-31fef09-78c7614]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.jar:git-Spigot-31fef09-78c7614]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.jar:git-Spigot-31fef09-78c7614]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_9_R1.World
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot-1.11.jar:git-Spigot-31fef09-78c7614]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.11.jar:git-Spigot-31fef09-78c7614]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
        ... 8 more

Thank's once again 
- Wandering Bread

**Comment by mwkaicz** [comment]
as you can see in the log, you are using Movecraft based on v1_9_R1, so you must take newer version of Movecraft, or turn on compatibility mode in config.yml

**Comment by WanderingBread** [comment]
That is the most updated version of Movecraft, right from PMC.
I am unsure if there is a more updated version.

**Comment by mwkaicz** [comment]
Sorry, I'm away from this plugin for some time, I wrote only what I se from your log. If you think that there is no newer version, try add 'compatibilityMode = true' to the config file.

**Comment by WanderingBread** [comment]
Hmm, That is already on in my config, however I have been told that apparently compatibility mode is broken.

**Comment by msummers123** [comment]
Oh, yeah, the PMC is out of date. Sorry about that, I'll get it updated. The newest version is now on SpigotMC:
https://www.spigotmc.org/resources/movecraft.31321/

**Comment by WanderingBread** [comment]
Thank you, I will check Spigot from now on.
