### ISSUE TITLE
Worldguard/movecraft error (I've looked for help everywhere I can)

### ISSUE THREAD

**Issue by jamesol1** [msummers123/Movecraft-3#241]
I have Installed spigot 1.10, 1.10 worldguard, 1.10 movecraft but keep getting this error literally spammed in my console. I have tried not having worldguard and it just spams something similar.
------------------------------------------------------------------------------------------------------------------
[22:59:21 WARN]: [Movecraft] Task #17 for Movecraft v5.0.0 generated an exceptio
n
java.lang.NoClassDefFoundError: net/minecraft/server/v1_9_R1/World
at net.countercraft.movecraft.async.AsyncManager.run(AsyncManager.java:1
525) ~[?:?]
at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.jav
a:71) ~[craftbukkit.jar:git-Spigot-6016ac7-10c10b3]
at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHe
artbeat(CraftScheduler.java:350) [craftbukkit.jar:git-Spigot-6016ac7-10c10b3]
at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:
741) [craftbukkit.jar:git-Spigot-6016ac7-10c10b3]
at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:
399) [craftbukkit.jar:git-Spigot-6016ac7-10c10b3]
at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:
672) [craftbukkit.jar:git-Spigot-6016ac7-10c10b3]
at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.jav
a:571) [craftbukkit.jar:git-Spigot-6016ac7-10c10b3]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_9_R1.World
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.
java:91) ~[craftbukkit.jar:git-Spigot-6016ac7-10c10b3]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.
java:86) ~[craftbukkit.jar:git-Spigot-6016ac7-10c10b3]
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
... 8 more

**Comment by galacticwarrior9** [comment]
Your issue is occuring because the plugin has not yet updated to 1.10. Luckily, updating it is very easy and can be done yourself.

**Comment by keough99** [comment]
Here's a link to the 1.10 version of movecraft https://www.spigotmc.org/resources/movecraft.31321/

**Comment by jamesol1** [comment]
I did download 5.0.2

**Comment by jamesol1** [comment]
**Thanks for your help... i tried that but i go spammed this error:**

[16:24:37 WARN]: [Movecraft] Task #17 for Movecraft v5.0.0 generated an exceptio
n
java.lang.NoClassDefFoundError: net/minecraft/server/v1_9_R1/World
        at net.countercraft.movecraft.async.AsyncManager.run(AsyncManager.java:1
525) ~[?:?]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.jav
a:71) ~[craftbukkit.jar:git-Spigot-6016ac7-10c10b3]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHe
artbeat(CraftScheduler.java:350) [craftbukkit.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:
741) [craftbukkit.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:
399) [craftbukkit.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:
672) [craftbukkit.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.jav
a:571) [craftbukkit.jar:git-Spigot-6016ac7-10c10b3]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_9_R1.World
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.
java:91) ~[craftbukkit.jar:git-Spigot-6016ac7-10c10b3]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.
java:86) ~[craftbukkit.jar:git-Spigot-6016ac7-10c10b3]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
        ... 8 more

**Comment by keough99** [comment]
Hmmm I'm not the error in my console anymore what Java version are you using?

**Comment by jamesol1** [comment]
Well I have just installed ''Recommended Version 8 Update 111'' and i get the same error. For the record it does seem to literally spam my console with the same message repeatedly.

**Comment by jamesol1** [comment]
When i remove world guard i get this message.

[15:48:47 INFO]: [Movecraft] Enabling Movecraft v5.0.0
[15:48:47 INFO]: [Movecraft] Recognized PilotTool setting of: 280
[15:48:47 INFO]: [Movecraft] CompatiblityMode is set to true
[15:48:47 INFO]: [Movecraft] Movecraft did not find a compatible version of Worl
dGuard. Disabling WorldGuard integration
[15:48:47 INFO]: [Movecraft] Found a compatible version of WorldEdit. Enabling W
orldEdit integration
[15:48:47 INFO]: [Movecraft] Movecraft did not find a compatible version of Town
y. Disabling Towny integration.
[15:48:47 INFO]: [Movecraft] Found a compatible version of Essentials. Enabling
Essentials integration.
[15:48:47 INFO]: [Movecraft] Found a compatible Vault plugin.
[15:48:47 ERROR]: Error occurred while enabling Movecraft v5.0.0 (Is it up to da
te?)
java.lang.NoClassDefFoundError: com/sk89q/worldguard/protection/flags/Flag
        at net.countercraft.movecraft.Movecraft.onEnable(Movecraft.java:350) ~[?
:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[c
raftbukkit.jar:git-Spigot-6016ac7-10c10b3]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader
.java:340) [craftbukkit.jar:git-Spigot-6016ac7-10c10b3]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManage
r.java:405) [craftbukkit.jar:git-Spigot-6016ac7-10c10b3]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugin(CraftServer.ja
va:362) [craftbukkit.jar:git-Spigot-6016ac7-10c10b3]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer
.java:322) [craftbukkit.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:
416) [craftbukkit.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:
381) [craftbukkit.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:
336) [craftbukkit.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.ja
va:270) [craftbukkit.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.jav
a:539) [craftbukkit.jar:git-Spigot-6016ac7-10c10b3]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldguard.protection.fla
gs.Flag
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_111]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.
java:101) ~[craftbukkit.jar:git-Spigot-6016ac7-10c10b3]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.
java:86) ~[craftbukkit.jar:git-Spigot-6016ac7-10c10b3]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
        ... 12 more
[15:48:47 INFO]: Server permissions file permissions.yml is empty, ignoring it
[15:48:47 INFO]: Done (4.787s)! For help, type "help" or "?"
[15:48:47 INFO]: [Vault] Checking for Updates ...
[15:48:47 INFO]: [Vault] No new version available
>

**Comment by keough99** [comment]
That's normal for startup

**Comment by jamesol1** [comment]
Building ships doesnt work though. AKA the stick doesnt let me fly a boat.

**Comment by keough99** [comment]
Do you have craft files installed into the types folder in the movecraft folder?

**Comment by jamesol1** [comment]
![pic1](https://cloud.githubusercontent.com/assets/24861741/21743101/3f2052c0-d4f3-11e6-953b-4c6fe0ddfd82.png)
I have tried giving the signs the ship names above but nothing works... also when i perform commands it just repeats them in the chat (console doesnt register them)

**Comment by jamesol1** [comment]
Does anybody know where I've gone wrong?

**Comment by Thomdare** [comment]
Do you have WorldGuard installed but not WorldEdit? That may be the problem. Plus, versions besides 1.9-1.9.2 must have compatibility mode **on**.
