### ISSUE TITLE
Error occurred while enabling Movecraft v5.5.0 (Is it up to date?)

### ISSUE THREAD

**Issue by OscarVDG** [msummers123/Movecraft-3#242]
When i launch my server with Movecraft i get this error message:

[22:56:32 INFO]: [Movecraft] Enabling Movecraft v5.5.0
[22:56:32 INFO]: [Movecraft] Recognized PilotTool setting of: 280
[22:56:32 INFO]: [Movecraft] CompatiblityMode is set to true
[22:56:32 INFO]: [Movecraft] Movecraft did not find a compatible version of WorldGuard. Disabling WorldGuard integration
[22:56:32 INFO]: [Movecraft] Found a compatible version of WorldEdit. Enabling WorldEdit integration
[22:56:32 INFO]: [Movecraft] Movecraft did not find a compatible version of Towny. Disabling Towny integration.
[22:56:32 INFO]: [Movecraft] Movecraft did not find a compatible version of Essentials. Disabling Essentials integration.
[22:56:32 INFO]: [Movecraft] Could not find compatible Vault plugin. Disabling Vault integration.
[22:56:32 ERROR]: Error occurred while enabling Movecraft v5.5.0 (Is it up to date?)
java.lang.NoClassDefFoundError: com/sk89q/worldguard/protection/flags/Flag
        at net.countercraft.movecraft.Movecraft.onEnable(Movecraft.java:385) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[spigot-1.9.jar:git-Spigot-d20369f-7fc5cd8]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.9.jar:git-Spigot-d20369f-7fc5cd8]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.9.jar:git-Spigot-d20369f-7fc5cd8]
        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361) [spigot-1.9.jar:git-Spigot-d20369f-7fc5cd8]
        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321) [spigot-1.9.jar:git-Spigot-d20369f-7fc5cd8]
        at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:411) [spigot-1.9.jar:git-Spigot-d20369f-7fc5cd8]
        at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:376) [spigot-1.9.jar:git-Spigot-d20369f-7fc5cd8]
        at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:331) [spigot-1.9.jar:git-Spigot-d20369f-7fc5cd8]
        at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:269) [spigot-1.9.jar:git-Spigot-d20369f-7fc5cd8]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527) [spigot-1.9.jar:git-Spigot-d20369f-7fc5cd8]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldguard.protection.flags.Flag
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_111]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.9.jar:git-Spigot-d20369f-7fc5cd8]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.9.jar:git-Spigot-d20369f-7fc5cd8]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
        ... 12 more

I have run it in version 1.9, 1.10.2 & 1.11.2 and they all give the same message. If i launch the server without World edit it still shows this. I also noticed that when i downloaded the version on spigot it said 5.0.2, but when launching the server it says that it's version 5.5.0. Any help would be appreciated. Thanks alot!

EDIT: I looked in the version history and tried the other too versions from spigot too. Could it be something in my config?

**Comment by mwkaicz** [comment]
Try to looking for another version of World Edit. WE is necessary for craft repairs.

**Comment by OscarVDG** [comment]
@mwkaicz Well since i launched it without WE and it gave the same error message that shouldn't be the problem. It also says that it found a compatible WE version. Then on the spigot page it says that movecraft doesn't require an other plugin to function.

**Comment by mwkaicz** [comment]
This is source/start of the error ```[22:56:32 ERROR]: Error occurred while enabling Movecraft v5.5.0 (Is it up to date?)
java.lang.NoClassDefFoundError: com/sk89q/worldguard/protection/flags/Flag
at net.countercraft.movecraft.Movecraft.onEnable(Movecraft.java:385) ~[?:?]``` it can't find part of WE, so your version of WE isn't compatible with that version with Movecraft was builded.

**Comment by OscarVDG** [comment]
@mwkaicz Yeah. I just launched it with WG and it worked! I was wrong about other plugins i guess. In either case, thanks alot!!!

**Comment by mwkaicz** [comment]
If you have no WE it will say the same, because it will still looking for same class ```com/sk89q/worldguard/protection/flags/Flag``` ... you must have WE, If you want use Movecraft.

**Comment by mwkaicz** [comment]
sorry I fooled you with WE/WG.
