### ISSUE TITLE
[java.lang.NoSuchFieldError: BLOCK_ANVIL_LAND] Vehicle and Air does not move

### ISSUE THREAD

**Issue by herm1ne** [msummers123/Movecraft-3#249]
Hi
I successfully get the ships move but I can't move Airskiff and following exceptions are thrown. (I didn't check other types tho)  
I use Movecraft 5.5.0 on Spigot 1.8.8  
```
[17:41:29 WARN]: org.apache.commons.lang.UnhandledException: Plugin Movecraft v5.5.0 generated an exception while executing task 40748
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchFieldError: BLOCK_ANVIL_LAND
        at net.countercraft.movecraft.async.translation.TranslationTask.fail(TranslationTask.java:969)
        at net.countercraft.movecraft.async.translation.TranslationTask.excecute(TranslationTask.java:253)
        at net.countercraft.movecraft.async.AsyncTask.run(AsyncTask.java:36)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
```
How can I solve this problem?  
Thanks in advance.

**Comment by pistols12** [comment]
Step 1, Upload craft file here.

Step 2, use a parser to check it  Parser: http://yaml-online-parser.appspot.com/

Step 3:  if you find no issues, or i have not responded to your craft file, try to use a older movecraft version, say 5.0.2 or 5.0.1  Spigot versions: https://www.spigotmc.org/resources/movecraft.31321/history

Step 4: bang head or computer on wall until i answer.
