### ISSUE TITLE
Random Double chest INVALID BLOCK crashing the server

### ISSUE THREAD

**Issue by FrozenBeard** [msummers123/Movecraft-3#259]
Movecraft version 5.5.0
PaperSpigot 1.11.2

Been using Movecraft for years and years, this ones been happening a lot recently.
https://pastebin.com/ecj4Rhin

```
[19:00:48] [Server thread/ERROR]: [Movecraft] ERROR: Double chest detected. This is not supported.
[19:00:48] [Server thread/WARN]: [Movecraft] Task #1260 for Movecraft v5.5.0 generated an exception
java.lang.IllegalArgumentException: INVALID BLOCK
    at net.countercraft.movecraft.utils.MapUpdateManager.getBlockDataPacket(MapUpdateManager.java:1095) ~[?:?]
    at net.countercraft.movecraft.utils.MapUpdateManager.run(MapUpdateManager.java:678) ~[?:?]
    at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.11.2.jar:git-Paper-1104]
    at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356) 
```

**Comment by cccm5** [comment]
Do you have a double chest on the craft, or is just randomly crashing?

**Comment by FrozenBeard** [comment]
I assume from the big text that says ERROR: Double chest detected a player tried to sail with a chest on board, and then movecraft threw a hissy fit and crashed the server.
