### ISSUE TITLE
Warn  Task #10   Movecraft not working

### ISSUE THREAD

**Issue by 1crimsonfalcon** [msummers123/Movecraft-3#261]
We are setting up movecraft for the first time and we cannot get it to work.  In the log there is an error for task # 10.
Here is the log showing the error, twice in this clip of the log:
**08.07 15:06:32 [Server] WARN [Movecraft] Task #10 for Movecraft v5.0.0 generated an exception**
08.07 15:06:32 [Server] INFO java.lang.NoClassDefFoundError: net/minecraft/server/v1_9_R1/Packet
08.07 15:06:32 [Server] INFO at net.countercraft.movecraft.async.AsyncManager.run(AsyncManager.java:1525) ~[?:?]
08.07 15:06:32 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.jar:git-Spigot-7228328-50b75cd]
08.07 15:06:32 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.12.jar:git-Spigot-7228328-50b75cd]
08.07 15:06:32 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot-1.12.jar:git-Spigot-7228328-50b75cd]
08.07 15:06:32 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.12.jar:git-Spigot-7228328-50b75cd]
08.07 15:06:32 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12.jar:git-Spigot-7228328-50b75cd]
08.07 15:06:32 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12.jar:git-Spigot-7228328-50b75cd]
08.07 15:06:32 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
08.07 15:06:32 [Server] INFO Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_9_R1.Packet
08.07 15:06:32 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot-1.12.jar:git-Spigot-7228328-50b75cd]
08.07 15:06:32 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.12.jar:git-Spigot-7228328-50b75cd]
08.07 15:06:32 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_112]
08.07 15:06:32 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_112]
08.07 15:06:32 [Server] INFO ... 8 more

08.07 15:06:36 [Server] INFO at net.countercraft.movecraft.async.AsyncManager.run(AsyncManager.java:1525) ~[?:?]
08.07 15:06:36 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.jar:git-Spigot-7228328-50b75cd]
08.07 15:06:36 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.12.jar:git-Spigot-7228328-50b75cd]
08.07 15:06:36 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot-1.12.jar:git-Spigot-7228328-50b75cd]
08.07 15:06:36 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.12.jar:git-Spigot-7228328-50b75cd]
08.07 15:06:36 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12.jar:git-Spigot-7228328-50b75cd]
08.07 15:06:36 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12.jar:git-Spigot-7228328-50b75cd]
08.07 15:06:36 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
08.07 15:06:36 [Server] INFO Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_9_R1.Packet
08.07 15:06:36 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot-1.12.jar:git-Spigot-7228328-50b75cd]
08.07 15:06:36 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.12.jar:git-Spigot-7228328-50b75cd]
08.07 15:06:36 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_112]
08.07 15:06:36 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_112]
08.07 15:06:36 [Server] INFO ... 8 more
**08.07 15:06:36 [Server] WARN [Movecraft] Task #10 for Movecraft v5.0.0 generated an exception**

[config.txt](https://github.com/msummers123/Movecraft-3/files/1133356/config.txt)

[permissions.txt](https://github.com/msummers123/Movecraft-3/files/1133355/permissions.txt)

Thank you for your help

**Comment by cccm5** [comment]
In the movecraft config set compatibility mode to true

**Comment by 1crimsonfalcon** [comment]
the error is still there

thanks though

**Comment by cccm5** [comment]
Are you sure it's the same error? activating compatibility mode should completely disable 1.9 specific code, which is what's causing the error here.

**Comment by 1crimsonfalcon** [comment]
No error now,   but still not working.   Says Insufficient permissions when clicking on sign for airship or airskiff,   both spelled lowercase.   I removed worldguard just to simplify and get rid of any extra errors.   Also correct the previous error with default by naming it Default capitalized under groups and that fixed that error, we are error free now.   Just one warning in the file.    I appreciate the help!   

Here are the files:
[latest .txt](https://github.com/msummers123/Movecraft-3/files/1134154/latest.txt)


[config.txt](https://github.com/msummers123/Movecraft-3/files/1134150/config.txt)


[permissions.txt](https://github.com/msummers123/Movecraft-3/files/1134151/permissions.txt)

**Comment by 1crimsonfalcon** [comment]
I found out there was an extra dash - in the moderator that admin inherits, and I removed that and it works!    Thank you  cccm5 for taking the time to try to help me!

**Comment by pistols12** [comment]
be sure to close ticket!
