### ISSUE TITLE
Movecraft 1.11.2 error

### ISSUE THREAD

**Issue by werff** [msummers123/Movecraft-3#264]
As the tittle says, I having this constant error for movecraft (the newest version) on 1.11.2
Using [Compatibilitymode: true]

The error

[14:17:32] [Server thread/INFO]: [Movecraft] Enabling Movecraft v5.5.0
[14:17:32] [Server thread/INFO]: [Movecraft] Recognized PilotTool setting of: 280
[14:17:32] [Server thread/INFO]: [Movecraft] CompatiblityMode is set to true
[14:17:32] [Server thread/INFO]: [Movecraft] Movecraft did not find a compatible version of WorldGuard. Disabling WorldGuard integration
[14:17:32] [Server thread/INFO]: [Movecraft] Movecraft did not find a compatible version of WorldEdit. Disabling WorldEdit integration
[14:17:32] [Server thread/INFO]: [Movecraft] Movecraft did not find a compatible version of Towny. Disabling Towny integration.
[14:17:32] [Server thread/INFO]: [Movecraft] Movecraft did not find a compatible version of Essentials. Disabling Essentials integration.
[14:17:32] [Server thread/INFO]: [Movecraft] Could not find compatible Vault plugin. Disabling Vault integration.
[14:17:32] [Server thread/ERROR]: Error occurred while enabling Movecraft v5.5.0 (Is it up to date?)
java.lang.NoClassDefFoundError: com/sk89q/worldguard/protection/flags/Flag
	at net.countercraft.movecraft.Movecraft.onEnable(Movecraft.java:385) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[craftbukkit.jar:git-Bukkit-6e3cec8]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:329) [craftbukkit.jar:git-Bukkit-6e3cec8]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [craftbukkit.jar:git-Bukkit-6e3cec8]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:361) [craftbukkit.jar:git-Bukkit-6e3cec8]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:323) [craftbukkit.jar:git-Bukkit-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:411) [craftbukkit.jar:git-Bukkit-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:372) [craftbukkit.jar:git-Bukkit-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:327) [craftbukkit.jar:git-Bukkit-6e3cec8]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:244) [craftbukkit.jar:git-Bukkit-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:521) [craftbukkit.jar:git-Bukkit-6e3cec8]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldguard.protection.flags.Flag
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_74]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:77) ~[craftbukkit.jar:git-Bukkit-6e3cec8]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62) ~[craftbukkit.jar:git-Bukkit-6e3cec8]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_74]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_74]
	... 12 more

**Comment by keough99** [comment]
Do you have the newest version off of spigot?

**Comment by pistols12** [comment]
I actually had something like this happen, and while I did not find out why the new movecraft jar would not work with my server yet, I did find out that reverting to an older one had 0 issues. Consider this in the mean time.

**Comment by pistols12** [comment]
Use the version 5.0.2 or 5.0.1 and see what comes of it.

https://www.spigotmc.org/resources/movecraft.31321/history
