### ISSUE TITLE
MoveCraft not working

### ISSUE THREAD

**Issue by EmeraldCrafts** [msummers123/Movecraft-3#268]
I'm trying to use Movecraft 6.0 with 1.11 but it won't enable.  Here is the log that says it won't work:

[18:56:46] [Server thread/INFO]: [Movecraft] Enabling Movecraft v6.0.0
[18:56:46] [Server thread/INFO]: [Movecraft] Recognized PilotTool setting of: 280
[18:56:46] [Server thread/INFO]: [Movecraft] CompatiblityMode is set to true
[18:56:46] [Server thread/INFO]: [Movecraft] Found a compatible version of WorldGuard. Enabling WorldGuard integration
[18:56:46] [Server thread/INFO]: [Movecraft] Settings: WorldGuardBlockMoveOnBuildPerm - true, WorldGuardBlockSinkOnPVPPerm - true
[18:56:46] [Server thread/INFO]: [Movecraft] Found a compatible version of WorldEdit. Enabling WorldEdit integration
[18:56:46] [Server thread/INFO]: [Movecraft] Movecraft did not find a compatible version of WGCustomFlags. Disabling WGCustomFlags integration.
[18:56:46] [Server thread/INFO]: [Movecraft] Movecraft did not find a compatible version of Towny. Disabling Towny integration.
[18:56:46] [Server thread/INFO]: [Movecraft] Found a compatible version of Essentials. Enabling Essentials integration.
[18:56:46] [Server thread/INFO]: [Movecraft] Found a compatible Vault plugin.
[18:56:46] [Server thread/ERROR]: Error occurred while enabling Movecraft v6.0.0 (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/server/v1_10_R1/Packet
	at net.countercraft.movecraft.Movecraft.onEnable(Movecraft.java:389) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[spigot_1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot_1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot_1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:376) [spigot_1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:326) [spigot_1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot_1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot_1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot_1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot_1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot_1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_77]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_10_R1.Packet
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot_1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot_1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_77]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_77]
	... 12 more

**Comment by pistols12** [comment]
I would make sure that your world guard and world edit jars are up-to-date as well. This plug-in requires worldguard and world edit as well to work.

**Comment by pistols12** [comment]
We have had other people have this issue and it was just the fact that they did not have those plugins installed. I would also make sure you have the plug-in called Vault.

**Comment by oh-noey** [comment]
Movecraft 6 only works on 1.10.2, try using a prior version
