### ISSUE TITLE
Spigot 1.9 movecraft 5.0.0

### ISSUE THREAD

**Issue by gingatron1000** [msummers123/Movecraft-3#274]
ive tried Spigot & CB 1.10.2 movecraft 6.0
Spigot & CB 1.10.0 / mvecraft 6.0
Spigot & CB 1.9 / mvecraft 5.0.2
Spigot & CB 1.9 / mvecraft 5.0.1
Spigot & CB 1.9 / mvecraft 5.0.0
and a few others

these are all just bench tests with nothing except the base server and the movecraft plugin, my actual server is hosted and simply says:
[ERROR]: Error occurred while enabling Movecraft v[whichever version number] (Is it up to date?) 

to be honest im kind of getting worn down so i might be missing something obvious but i always get the same error:

[16:58:15 INFO]: [Movecraft] Enabling Movecraft v5.0.0
[16:58:15 INFO]: [Movecraft] Recognized PilotTool setting of: 280
[16:58:15 INFO]: [Movecraft] CompatiblityMode is set to false
[16:58:15 INFO]: [Movecraft] Movecraft did not find a compatible version of WorldGuard. Disabling WorldGuard integration
[16:58:15 INFO]: [Movecraft] Movecraft did not find a compatible version of WorldEdit. Disabling WorldEdit integration
[16:58:15 INFO]: [Movecraft] Movecraft did not find a compatible version of Towny. Disabling Towny integration.
[16:58:15 INFO]: [Movecraft] Movecraft did not find a compatible version of Essentials. Disabling Essentials integration.
[16:58:15 INFO]: [Movecraft] Could not find compatible Vault plugin. Disabling Vault integration.
[16:58:15 ERROR]: Error occurred while enabling Movecraft v5.0.0 (Is it up to date?)
java.lang.NoClassDefFoundError: com/sk89q/worldguard/protection/flags/Flag
        at net.countercraft.movecraft.Movecraft.onEnable(Movecraft.java:350) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[craftbukkit.jar:git-Bukkit-44216f1]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [craftbukkit.jar:git-Bukkit-44216f1]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [craftbukkit.jar:git-Bukkit-44216f1]
        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:346) [craftbukkit.jar:git-Bukkit-44216f1]
        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:318) [craftbukkit.jar:git-Bukkit-44216f1]
        at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:403) [craftbukkit.jar:git-Bukkit-44216f1]
        at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:368) [craftbukkit.jar:git-Bukkit-44216f1]
        at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:323) [craftbukkit.jar:git-Bukkit-44216f1]
        at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:241) [craftbukkit.jar:git-Bukkit-44216f1]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:506) [craftbukkit.jar:git-Bukkit-44216f1]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldguard.protection.flags.Flag
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_151]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:77) ~[craftbukkit.jar:git-Bukkit-44216f1]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62) ~[craftbukkit.jar:git-Bukkit-44216f1]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_151]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_151]
        ... 12 more

the only thing i can be sure of is each time i load up the plugin i doesnt create a types folder so either that means i need to do it manually or its broken but even if i add types it fails with the same error so probably not relevent.

**Comment by gingatron1000** [comment]
i should add, i have had a movecraft server running in the past but it was 2014 so things have probably changed a bit since then.

**Comment by gingatron1000** [comment]
i got it working, worldedit for bukkit (the forge one doesnt work, probably obviously to most but i didnt catch that at first) worldguard then installed movecraft 6 on 1.10
