### ISSUE TITLE
Issue when initializing Movecraft (1.12.2)

### ISSUE THREAD

**Issue by brandonyoungdev** [msummers123/Movecraft-3#278]
Whenever Spigot.jar launches it always returns this error. I tried multiple versions of Spigot.jar and multiple versions of movecraft. (Minecraft 1.12.2)

**Error:**
[17:35:03` ERROR]: Error occurred while enabling Movecraft v6.0.0 (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/server/v1_10_R1/World
        at net.countercraft.movecraft.Movecraft.onEnable(Movecraft.java:389) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[minecraft_server.jar:git-Spigot-4bd94dc-3a482bd]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [minecraft_server.jar:git-Spigot-4bd94dc-3a482bd]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [minecraft_server.jar:git-Spigot-4bd94dc-3a482bd]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [minecraft_server.jar:git-Spigot-4bd94dc-3a482bd]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [minecraft_server.jar:git-Spigot-4bd94dc-3a482bd]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.reload(CraftServer.java:752) [minecraft_server.jar:git-Spigot-4bd94dc-3a482bd]
        at org.bukkit.Bukkit.reload(Bukkit.java:525) [minecraft_server.jar:git-Spigot-4bd94dc-3a482bd]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27) [minecraft_server.jar:git-Spigot-4bd94dc-3a482bd]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [minecraft_server.jar:git-Spigot-4bd94dc-3a482bd]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) [minecraft_server.jar:git-Spigot-4bd94dc-3a482bd]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:634) [minecraft_server.jar:git-Spigot-4bd94dc-3a482bd]
        at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:444) [minecraft_server.jar:git-Spigot-4bd94dc-3a482bd]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:407) [minecraft_server.jar:git-Spigot-4bd94dc-3a482bd]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [minecraft_server.jar:git-Spigot-4bd94dc-3a482bd]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [minecraft_server.jar:git-Spigot-4bd94dc-3a482bd]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_10_R1.World
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:105) ~[minecraft_server.jar:git-Spigot-4bd94dc-3a482bd]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[minecraft_server.jar:git-Spigot-4bd94dc-3a482bd]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
        ... 17 more

**Comment by mwkaicz** [comment]
You have spigot 1.12.2, but your Movecraft version is for 1.10

**Comment by vellak** [comment]
Set your movecraft version to 5.0.2 and it should work fine, it worked for me when I set it up today

**Comment by lukejn123** [comment]
hey, we're having the same issue; but cant download the v5.0.2 maybe because we're on bukkit...
