### ISSUE TITLE
WG compatibility problem and problems with Crates - summary of AJCStriker/Movecraft-3/issues/137

### ISSUE THREAD

**Issue by mwkaicz** [msummers123/Movecraft-3#71]
This is summary of https://github.com/AJCStriker/Movecraft-3/issues/137

WG - there should be version check, or something similar:

```
23.12 01:13:13 [Server] INFO at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftTask.run(CraftTask.java:53) ~[craftbukkit-1.7.9-3092.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
23.12 01:13:13 [Server] INFO at net.countercraft.movecraft.async.AsyncManager.run(AsyncManager.java:508) ~[?:?]
23.12 01:13:13 [Server] INFO at net.countercraft.movecraft.async.AsyncManager.processSinking(AsyncManager.java:390) ~[?:?]
23.12 01:13:13 [Server] INFO at net.countercraft.movecraft.async.AsyncManager.isRegionBlockedPVP(AsyncManager.java:365) ~[?:?]
23.12 01:13:13 [Server] INFO java.lang.IncompatibleClassChangeError: Found class com.sk89q.worldguard.protection.ApplicableRegionSet, but interface was expected
```

WG - prevents sinking in PVP areas too (with combination of plugins WG and Towny)

Crates - again and again, problems with creating (In my case with Spigot 1.8)
            - also problem with unexisting records in crates file (add some exception for null result)

**Comment by msummers123** [comment]
I would like to get this issue closed if there are no further questions?

**Comment by chillerkraft** [comment]
yep im good ty
