### ISSUE TITLE
New versions of Movecraft crashing with older versions.

### ISSUE THREAD

**Issue by striker0822** [msummers123/Movecraft-3#86]
Hello there, I seem to be having problems with the newest versions of movecraft. When I try to pilot a ship with the newest version running  compatibility mode, It just lags and then crashes. Heres a small bit from my server while running the newer plugin. Sorry its so long, THo

[20:18:50] [Server thread/INFO]: [Movecraft] Enabling Movecraft v3.1.X70
[20:18:50] [Server thread/INFO]: [Movecraft] Recognized PilotTool setting of: 280
[20:18:50] [Server thread/INFO]: [Movecraft] CompatiblityMode is set to true
[20:18:50] [Server thread/INFO]: [Movecraft] Found a compatible version of WorldGuard. Enabling WorldGuard integration
[20:18:50] [Server thread/INFO]: [Movecraft] Settings: WorldGuardBlockMoveOnBuildPerm - true, WorldGuardBlockSinkOnPVPPerm - true
[20:18:50] [Server thread/ERROR]: [Movecraft] ***ERROR PARSING CRAFT FILE FROM DIRECTORY : C:\Users\******\Desktop\Server\plugins\Movecraft\types\Airship.craft***
[20:18:50] [Server thread/WARN]: java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Integer
[20:18:50] [Server thread/WARN]: 	at net.countercraft.movecraft.craft.CraftType.integerFromObject(CraftType.java:79)
[20:18:50] [Server thread/WARN]: 	at net.countercraft.movecraft.craft.CraftType.parseCraftDataFromFile(CraftType.java:175)
[20:18:50] [Server thread/WARN]: 	at net.countercraft.movecraft.craft.CraftType.<init>(CraftType.java:68)
[20:18:50] [Server thread/WARN]: 	at net.countercraft.movecraft.craft.CraftManager.initCraftTypes(CraftManager.java:68)
[20:18:50] [Server thread/WARN]: 	at net.countercraft.movecraft.craft.CraftManager.<init>(CraftManager.java:47)
[20:18:50] [Server thread/WARN]: 	at net.countercraft.movecraft.craft.CraftManager.<clinit>(CraftManager.java:36)
[20:18:50] [Server thread/WARN]: 	at net.countercraft.movecraft.Movecraft.onEnable(Movecraft.java:138)
[20:18:50] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[20:18:50] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335)
[20:18:50] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[20:18:50] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:356)
[20:18:50] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:316)
[20:18:50] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:402)
[20:18:50] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:370)
[20:18:50] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:325)
[20:18:50] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:211)
[20:18:50] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:494)
[20:18:50] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[20:18:50] [Server thread/ERROR]: [Movecraft] ***ERROR PARSING CRAFT FILE FROM DIRECTORY : C:\Users\Dakota\Desktop\Server\plugins\Movecraft\types\BigSubAirship.craft***
[20:18:50] [Server thread/WARN]: java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Integer
[20:18:50] [Server thread/WARN]: 	at net.countercraft.movecraft.craft.CraftType.integerFromObject(CraftType.java:79)
[20:18:50] [Server thread/WARN]: 	at net.countercraft.movecraft.craft.CraftType.parseCraftDataFromFile(CraftType.java:175)
[20:18:50] [Server thread/WARN]: 	at net.countercraft.movecraft.craft.CraftType.<init>(CraftType.java:68)
[20:18:50] [Server thread/WARN]: 	at net.countercraft.movecraft.craft.CraftManager.initCraftTypes(CraftManager.java:68)
[20:18:50] [Server thread/WARN]: 	at net.countercraft.movecraft.craft.CraftManager.<init>(CraftManager.java:47)
[20:18:50] [Server thread/WARN]: 	at net.countercraft.movecraft.craft.CraftManager.<clinit>(CraftManager.java:36)
[20:18:50] [Server thread/WARN]: 	at net.countercraft.movecraft.Movecraft.onEnable(Movecraft.java:138)
[20:18:50] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[20:18:50] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335)
[20:18:50] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[20:18:50] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:356)
[20:18:50] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:316)
[20:18:50] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:402)
[20:18:50] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:370)
[20:18:50] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:325)
[20:18:50] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:211)
[20:18:50] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:494)
[20:18:50] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[20:18:50] [Server thread/INFO]: [Movecraft] Loaded 37 Craft files
[20:18:50] [Server thread/INFO]: [Movecraft] Submitted statistics to mcstats.org succesfully. Thank you for your support.
[20:18:50] [Server thread/INFO]: [Movecraft] [V 3.1.X70] has been enabled.

**Comment by TylerS1066** [comment]
It seems that your .craft files are making movecraft try to put a long (data type between -9223372036854775808 and 9223372036854775808) value into a int (-2147483648 to 2147483648)

Do your .craft files have numbers that big in them?
It also seems to be only the BigSubAirship.craft and the Aiship.craft, try posting them on pastebin so we can take a look at them

**Comment by striker0822** [comment]
I had a larger value of the number of blocks that were allowed to be picked up by an airship, would that be the problem?

**Comment by msummers123** [comment]
Well, it depends on how large we are talking. More than 2 billion? Yeah, the craft interpreter won't even be able to read it. That could be what is happening.

Of course, I don't care if you are using every processing node in the NSA, there is no way you are moving a 2B block ship >.>

**Comment by striker0822** [comment]
Ah, found the problem. With the new movecraft engine my number was a block too large. Problem corrected. Thank you.

**Comment by TylerS1066** [comment]
lol a 2 billion block ship
