### ISSUE TITLE
/cruise - low priority

### ISSUE THREAD

**Issue by mwkaicz** [msummers123/Movecraft-3#91]
needs little bit care around missing argument

```
[23:00:06 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cruise' in plugin Movecraft v3.1.X73
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-c46583f-e6f9fd4]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-c46583f-e6f9fd4]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[spigot.jar:git-Spigot-c46583f-e6f9fd4]
        at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115) [spigot.jar:git-Spigot-c46583f-e6f9fd4]
        at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950) [spigot.jar:git-Spigot-c46583f-e6f9fd4]
        at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [spigot.jar:git-Spigot-c46583f-e6f9fd4]
        at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [spigot.jar:git-Spigot-c46583f-e6f9fd4]
        at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot.jar:git-Spigot-c46583f-e6f9fd4]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_25]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_25]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:683) [spigot.jar:git-Spigot-c46583f-e6f9fd4]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot.jar:git-Spigot-c46583f-e6f9fd4]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot.jar:git-Spigot-c46583f-e6f9fd4]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot.jar:git-Spigot-c46583f-e6f9fd4]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
        at net.countercraft.movecraft.listener.CommandListener.onCommand(CommandListener.java:224) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-c46583f-e6f9fd4]
        ... 14 more
>
```

**Comment by mwkaicz** [comment]
maybe when argument isn't set - then get default cruise direction from the player facing (view direction).

**Comment by TylerS1066** [comment]
I like mwkaicz's suggestion

**Comment by Pocketkid2** [comment]
This has been fixed in a recent commit, can we close this?
